import { type Attachment } from './attachment';

export type EquipmentStatus = 'running' | 'repairing' | 'fault';

export type Equipment = {
  ImageIds?: string[];
  Attachments?: Attachment[];
  RepairCount?: number;
  CurrentMonthRepairCount?: number;
  MaintenanceCount?: number;
  MaintenanceOrder?: string;
  RepairOrder?: string;
  UseManagerName?: string;
  StartDate1?: string;
  DeptName?: string;
  Runtime?: string;
  Health?: number;
  StatusText?: string;
  MachineTypeId?: string;
  MachineNo?: string;
  MachineName?: string;
  Status: EquipmentStatus;
  UseDeptId?: string;
  UseManeageId?: string;
  RepairManeageId?: string;
  BrandModel?: string;
  Manufacturer?: string;
  Supplier?: string;
  Location?: string;
  AnnualInspection?: boolean;
  AnnualInspectionDate?: Date;
  CommissioningDate?: Date;
  StopDate?: Date;
  ImageId?: string;
  Remark?: string;
  IsDeleted?: boolean;
  IsActive?: boolean;
  ImportDataId?: string;
  ModificationNum?: number;
  Tag?: number;
  GroupId?: string;
  CompanyId?: string;
  AuditStatus?: string;
  CurrentNode?: string;
  CreatedBy?: string;
  CreatedTime?: Date;
  UpdateBy?: string;
  UpdateTime?: Date;
  ModuleCode?: string;
  MachineType?: string;
  ID: string;
  RepairStats: EquipmentRepairStats[];
};
export type EquipmentRepairStats = {
  value: string;
  label: string;
  bgColor: string;
  textColor: string;
};
